set(CGLM_SEARCH_PATHS ${EXTERNAL_DIR})

find_path(
    CGLM_INCLUDE_PATH
    NAMES cglm/cglm.h
    PATHS ${CGLM_SEARCH_PATHS}
    PATH_SUFFIXES include
)

set(CGLM_FOUND "NO")

if(CGLM_INCLUDE_PATH)
    set(CGLM_FOUND "YES")
    message("EXTERNAL LIBRARY 'CGLM' FOUND")
else()
    message("ERROR: EXTERNAL LIBRARY 'CGLM' NOT FOUND")
endif(CGLM_INCLUDE_PATH)
